# run docker hoster from asami76
version: '3.7'

services:

  hoster:
    image: asami76/docker-hoster
    container_name: hoster
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

  jupyter:
    image: asami76/jupyter
    container_name: jupyter
    hostname: jupyter
    restart: unless-stopped
    volumes:
      - ./notebooks:/home/jovyan
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000

